# Generated by Django 5.2.3 on 2025-06-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='promotion_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='resignation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
