# Generated by Django 5.2.3 on 2025-06-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_analytics', '0002_employee_promotion_count_employee_resignation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
